plugins:
  jwt_enabled:
    default: false
    client: true
  jwt_secret:
    default: ""
    client: true
  jwt_auth_url:
    default: ""
    client: true
  jwt_algorithm:
   default: "RS256"
   client: true